/**
 * Kafka Exception Handling
 * This is an application to show kafka data.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: balu.vyamajala@amway.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export class PartitionOffset {
    partition?: number;
    offset?: number;
    public constructor(partition: number, offset?: number) {
        this.partition = partition;
        if (offset != undefined) this.offset = offset;
        else this.offset = 0;
    }
}
